// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package icons

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/alipan.png
var resourceAlipanPngData []byte
var resourceAlipanPng = &fyne.StaticResource{
	StaticName:    "assets/alipan.png",
	StaticContent: resourceAlipanPngData,
}

//go:embed assets/baidu.ico
var resourceBaiduIcoData []byte
var resourceBaiduIco = &fyne.StaticResource{
	StaticName:    "assets/baidu.ico",
	StaticContent: resourceBaiduIcoData,
}

//go:embed assets/ecloud.ico
var resourceEcloudIcoData []byte
var resourceEcloudIco = &fyne.StaticResource{
	StaticName:    "assets/ecloud.ico",
	StaticContent: resourceEcloudIcoData,
}

//go:embed assets/logo.png
var resourceLogoPngData []byte
var resourceLogoPng = &fyne.StaticResource{
	StaticName:    "assets/logo.png",
	StaticContent: resourceLogoPngData,
}

//go:embed assets/quark.ico
var resourceQuarkIcoData []byte
var resourceQuarkIco = &fyne.StaticResource{
	StaticName:    "assets/quark.ico",
	StaticContent: resourceQuarkIcoData,
}

//go:embed assets/thunder.ico
var resourceThunderIcoData []byte
var resourceThunderIco = &fyne.StaticResource{
	StaticName:    "assets/thunder.ico",
	StaticContent: resourceThunderIcoData,
}

//go:embed assets/yyw.ico
var resourceYywIcoData []byte
var resourceYywIco = &fyne.StaticResource{
	StaticName:    "assets/yyw.ico",
	StaticContent: resourceYywIcoData,
}
