// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package icons

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/alipan.png
var resourceAlipanPngData []byte
var resourceAlipanPng = &fyne.StaticResource{
	StaticName:    "assets/alipan.png",
	StaticContent: resourceAlipanPngData,
}

//go:embed assets/baidu.png
var resourceBaiduPngData []byte
var resourceBaiduPng = &fyne.StaticResource{
	StaticName:    "assets/baidu.png",
	StaticContent: resourceBaiduPngData,
}

//go:embed assets/bg.png
var resourceBgPngData []byte
var resourceBgPng = &fyne.StaticResource{
	StaticName:    "assets/bg.png",
	StaticContent: resourceBgPngData,
}

//go:embed assets/chrome.png
var resourceChromePngData []byte
var resourceChromePng = &fyne.StaticResource{
	StaticName:    "assets/chrome.png",
	StaticContent: resourceChromePngData,
}

//go:embed assets/ecloud.png
var resourceEcloudPngData []byte
var resourceEcloudPng = &fyne.StaticResource{
	StaticName:    "assets/ecloud.png",
	StaticContent: resourceEcloudPngData,
}

//go:embed assets/logo.png
var resourceLogoPngData []byte
var resourceLogoPng = &fyne.StaticResource{
	StaticName:    "assets/logo.png",
	StaticContent: resourceLogoPngData,
}

//go:embed assets/quark.png
var resourceQuarkPngData []byte
var resourceQuarkPng = &fyne.StaticResource{
	StaticName:    "assets/quark.png",
	StaticContent: resourceQuarkPngData,
}

//go:embed assets/thunder.png
var resourceThunderPngData []byte
var resourceThunderPng = &fyne.StaticResource{
	StaticName:    "assets/thunder.png",
	StaticContent: resourceThunderPngData,
}

//go:embed assets/uc.png
var resourceUcPngData []byte
var resourceUcPng = &fyne.StaticResource{
	StaticName:    "assets/uc.png",
	StaticContent: resourceUcPngData,
}

//go:embed assets/yd.png
var resourceYdPngData []byte
var resourceYdPng = &fyne.StaticResource{
	StaticName:    "assets/yd.png",
	StaticContent: resourceYdPngData,
}

//go:embed assets/yes.png
var resourceYesPngData []byte
var resourceYesPng = &fyne.StaticResource{
	StaticName:    "assets/yes.png",
	StaticContent: resourceYesPngData,
}

//go:embed assets/yyw.png
var resourceYywPngData []byte
var resourceYywPng = &fyne.StaticResource{
	StaticName:    "assets/yyw.png",
	StaticContent: resourceYywPngData,
}
